import Head from "next/head";
import Link from "next/link";

import { getPostAndPortfolio } from "../lib/data";

export const getStaticProps = async () => {
  const data = await getPostAndPortfolio();
  return {
    props: {
      data,
    },
  };
};

export default function Home({ data }) {
  console.log(data);
  return (
    <>
      <Head>
        <title>Awesome Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {data?.portfolios.map((item) => (
          <div key={item.slug}>
            <Link href={`/portfolio/${item.slug}`}>{item.title}</Link>
          </div>
        ))}
      </div>

      <div className="mt-10">
        {data?.posts.map((item) => (
          <div key={item.slug}>
            <Link href={`/blog/${item.slug}`}>{item.title}</Link>
          </div>
        ))}
      </div>
    </>
  );
}
